version: '{build}'  

pull_requests:  
  do_not_increment_build_number: true
  
branches:  
  only:
  - master
  
nuget:  
  disable_publish_on_pr: true
  
build_script:
  - cmd: .\psake.bat ci
  
test: off  

artifacts:  
  - path: .\artifacts\**\*.nupkg
    name: NuGet
    
cache:
  - '%LOCALAPPDATA%\Microsoft\dotnet'
  
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/babelshift-ci/api/v2/package
    api_key:
      secure: zI5gnqOnLVuIzNHVG1eiCpi5mEsT1i6AvwOHwIIm27NOURZFnCHhwG3SE49f0f88
    skip_symbols: true
    on:
      branch: master
    
  - provider: NuGet
    name: production
    api_key:
      secure: vIHuOdB4aYJEqNACb3jjCg3m/qZLqpwYlruu8J0BOiX81lRrmussVEUqiWRBTrRQ
    on:
      branch: master
      appveyor_repo_tag: true