version: 1.0.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: SourceSchemaParser.sln
  publish_nuget: true
  include_nuget_references: true
  
cache:
  - packages -> **\packages.config
  
before_build:
  - cmd: nuget restore